/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    menus: Menu;
    users: User;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    colors: Color;
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    colors: ColorsSelect<false> | ColorsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  layout?: SectionBlockProps[] | null;
  /**
   * Title tag appearing in Google results (recommended up to 60 characters).
   */
  seoTitle?: string | null;
  /**
   * Meta description for search engines (recommended up to 160 characters).
   */
  seoDescription?: string | null;
  /**
   * Social media share image.
   */
  seoImage?: (number | null) | Media;
  /**
   * Only lowercase letters, numbers, and hyphens are allowed. Leaving it blank will automatically generate it from the title.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionBlockProps".
 */
export interface SectionBlockProps {
  blocks?: (BlockHolderLevel0BlockProps | PostsBlockProps)[] | null;
  settings?: {
    /**
     * Optional — custom ID / anchor
     */
    htmlId?: string | null;
    /**
     * Optional — extra class name(s) for custom styling
     */
    customClassName?: string | null;
    viewport?: ('auto' | 'full') | null;
    widthType?: ('fullWidth' | 'boxed') | null;
    /**
     * Optional — vertical alignment
     */
    alignment?: ('top' | 'center' | 'bottom') | null;
    containerType?: ('container-xl' | 'container-lg' | 'container' | 'container-xs') | null;
    spacing?: {
      paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
      paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
      marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
      marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    };
    background?: {
      type?: ('blank' | 'color' | 'gradient' | 'image' | 'video') | null;
      colorTheme?: string | null;
      gradientTheme?: ('warm' | 'cool') | null;
      image?: (number | null) | Media;
      /**
       * Plays muted, looped, and autoplaying — no sound controls.
       */
      video?: (number | null) | Media;
      overlay?: {
        enabled?: boolean | null;
        color?: string | null;
        /**
         * 0 - 100
         */
        opacity?: number | null;
      };
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockHolderLevel0BlockProps".
 */
export interface BlockHolderLevel0BlockProps {
  atoms?:
    | (
        | BlockHolderLevel1BlockProps
        | MenuBlockProps
        | HeadingBlockProps
        | RichTextBlockProps
        | ImageBlockProps
        | VideoBlockProps
        | ButtonBlockProps
        | TabsBlockProps
        | SliderBlockProps
        | AccordionBlockProps
        | CTABlockProps
        | HeroBlockProps
        | ServicesBlockProps
        | ProcessBlockProps
        | GalleryBlockProps
        | InstagramStripBlockProps
        | ContactBlockProps
        | NavbarBlockProps
        | FooterColumnsBlockProps
        | AboutBlockProps
        | PricingBlockProps
        | FAQBlockProps
        | TestimonialsBlockProps
        | StatsBlockProps
        | TeamBlockProps
        | FormBlockProps
        | DividerBlockProps
      )[]
    | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  layout?: ('block' | 'flex' | 'grid') | null;
  verticalAlignment?: ('top' | 'middle' | 'bottom') | null;
  flexVariant?: ('row' | 'row-reverse' | 'row-wrap' | 'column' | 'column-reverse' | 'column-center') | null;
  gridVariant?: ('auto' | 'col-2' | 'col-3') | null;
  gap?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blockHolder0';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockHolderLevel1BlockProps".
 */
export interface BlockHolderLevel1BlockProps {
  atoms?:
    | (
        | BlockHolderLevel2BlockProps
        | MenuBlockProps
        | HeadingBlockProps
        | RichTextBlockProps
        | ImageBlockProps
        | VideoBlockProps
        | ButtonBlockProps
        | TabsBlockProps
        | SliderBlockProps
        | AccordionBlockProps
        | CTABlockProps
        | HeroBlockProps
        | ServicesBlockProps
        | ProcessBlockProps
        | GalleryBlockProps
        | InstagramStripBlockProps
        | ContactBlockProps
        | NavbarBlockProps
        | FooterColumnsBlockProps
        | AboutBlockProps
        | PricingBlockProps
        | FAQBlockProps
        | TestimonialsBlockProps
        | StatsBlockProps
        | TeamBlockProps
        | FormBlockProps
        | DividerBlockProps
      )[]
    | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  layout?: ('block' | 'flex' | 'grid') | null;
  verticalAlignment?: ('top' | 'middle' | 'bottom') | null;
  flexVariant?: ('row' | 'row-reverse' | 'row-wrap' | 'column' | 'column-reverse' | 'column-center') | null;
  gridVariant?: ('auto' | 'col-2' | 'col-3') | null;
  gap?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blockHolder1';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockHolderLevel2BlockProps".
 */
export interface BlockHolderLevel2BlockProps {
  atoms?:
    | (
        | MenuBlockProps
        | HeadingBlockProps
        | RichTextBlockProps
        | ImageBlockProps
        | VideoBlockProps
        | ButtonBlockProps
        | TabsBlockProps
        | SliderBlockProps
        | AccordionBlockProps
        | CTABlockProps
        | HeroBlockProps
        | ServicesBlockProps
        | ProcessBlockProps
        | GalleryBlockProps
        | InstagramStripBlockProps
        | ContactBlockProps
        | NavbarBlockProps
        | FooterColumnsBlockProps
        | AboutBlockProps
        | PricingBlockProps
        | FAQBlockProps
        | TestimonialsBlockProps
        | StatsBlockProps
        | TeamBlockProps
        | FormBlockProps
        | DividerBlockProps
      )[]
    | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  layout?: ('block' | 'flex' | 'grid') | null;
  verticalAlignment?: ('top' | 'middle' | 'bottom') | null;
  flexVariant?: ('row' | 'row-reverse' | 'row-wrap' | 'column' | 'column-reverse' | 'column-center') | null;
  gridVariant?: ('auto' | 'col-2' | 'col-3') | null;
  gap?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blockHolder2';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MenuBlockProps".
 */
export interface MenuBlockProps {
  /**
   * Select a menu from the Menus collection
   */
  menu: number | Menu;
  orientation?: ('horizontal' | 'vertical') | null;
  variant?: ('default' | 'minimal' | 'pills') | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'menu';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: number;
  name: string;
  items?:
    | {
        /**
         * Select a page
         */
        page?: (number | null) | Page;
        /**
         * Optional — element ID on the page (without #)
         */
        anchor?: string | null;
        /**
         * Full URL (https://...)
         */
        url?: string | null;
        label?: string | null;
        type?: ('internal' | 'external') | null;
        newTab?: boolean | null;
        children?:
          | {
              page?: (number | null) | Page;
              anchor?: string | null;
              url?: string | null;
              label: string;
              type?: ('internal' | 'external') | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  orientation?: ('horizontal' | 'vertical') | null;
  variant?: 'default' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeadingBlockProps".
 */
export interface HeadingBlockProps {
  title?: string | null;
  variant?: ('default' | 'center' | 'right') | null;
  titleTag?: ('h1' | 'h2' | 'h3' | 'h4' | 'p' | 'span') | null;
  color?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heading';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlockProps".
 */
export interface RichTextBlockProps {
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  variant?: ('default' | 'center' | 'right') | null;
  color?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlockProps".
 */
export interface ImageBlockProps {
  image?: (number | null) | Media;
  linkType?: ('none' | 'internal' | 'external') | null;
  internalLink?: (number | null) | Page;
  externalUrl?: string | null;
  newTab?: boolean | null;
  aspectRatio?: ('auto' | '1/1' | '3/2' | '4/3' | '16/9' | '2/3' | '3/4' | '9/16' | 'custom') | null;
  /**
   * Format: 16/9, 4/3, 1/1...
   */
  customAspectRatio?: string | null;
  overlay?: {
    enabled?: boolean | null;
    color?: string | null;
    /**
     * 0 - 100
     */
    opacity?: number | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlockProps".
 */
export interface VideoBlockProps {
  sourceType?: ('upload' | 'url') | null;
  file?: (number | null) | Media;
  /**
   * Shown before playback starts, so the video file itself is only fetched once a visitor presses play.
   */
  poster?: (number | null) | Media;
  /**
   * YouTube, Vimeo, or a direct video file link.
   */
  url?: string | null;
  aspectRatio?: ('16/9' | '4/3' | '1/1' | '9/16' | 'custom') | null;
  /**
   * Format: 16/9, 4/3, 1/1...
   */
  customAspectRatio?: string | null;
  controls?: boolean | null;
  /**
   * Forces mute — browsers block sound-on autoplay.
   */
  autoplay?: boolean | null;
  loop?: boolean | null;
  muted?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonBlockProps".
 */
export interface ButtonBlockProps {
  text: string;
  linkType?: ('internal' | 'external') | null;
  internalLink?: (number | null) | Page;
  externalUrl?: string | null;
  newTab?: boolean | null;
  variant?: ('primary' | 'secondary' | 'ghost' | 'outline') | null;
  hasIcon?: boolean | null;
  iconType?: ('picker' | 'customSvg') | null;
  icon?: string | null;
  customSvg?: (number | null) | Media;
  iconPosition?: ('left' | 'right') | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'button';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabsBlockProps".
 */
export interface TabsBlockProps {
  items?:
    | {
        blocks?: (HeadingBlockProps | RichTextBlockProps | ImageBlockProps | ButtonBlockProps)[] | null;
        label: string;
        defaultActive?: boolean | null;
        hasIcon?: boolean | null;
        iconType?: ('picker' | 'customSvg') | null;
        icon?: string | null;
        customSvg?: (number | null) | Media;
        iconPosition?: ('left' | 'right') | null;
        id?: string | null;
      }[]
    | null;
  orientation?: ('horizontal' | 'vertical') | null;
  variant?: ('default' | 'full' | 'minimal') | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'tabs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SliderBlockProps".
 */
export interface SliderBlockProps {
  settings?: {
    orientation?: ('horizontal' | 'vertical') | null;
    /**
     * Space between slides in px
     */
    spaceBetween?: number | null;
    slidesPerView?: number | null;
  };
  slides?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image' | 'video') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    /**
     * Plays muted, looped, and autoplaying — no sound controls.
     */
    video?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'slider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlockProps".
 */
export interface AccordionBlockProps {
  items?:
    | {
        blocks?: (HeadingBlockProps | RichTextBlockProps | ImageBlockProps | ButtonBlockProps)[] | null;
        label: string;
        defaultOpen?: boolean | null;
        hasIcon?: boolean | null;
        iconType?: ('picker' | 'customSvg') | null;
        icon?: string | null;
        customSvg?: (number | null) | Media;
        iconPosition?: ('left' | 'right') | null;
        id?: string | null;
      }[]
    | null;
  allowMultiple?: boolean | null;
  variant?: ('default' | 'bordered' | 'minimal') | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image' | 'video') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    /**
     * Plays muted, looped, and autoplaying — no sound controls.
     */
    video?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlockProps".
 */
export interface CTABlockProps {
  title: string;
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  buttons?: ButtonBlockProps[] | null;
  alignment?: ('left' | 'center') | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image' | 'video') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    /**
     * Plays muted, looped, and autoplaying — no sound controls.
     */
    video?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlockProps".
 */
export interface HeroBlockProps {
  eyebrow?: string | null;
  title: string;
  /**
   * Rendered on its own line, wrapped in <em>.
   */
  highlightedTitle?: string | null;
  description?: string | null;
  buttons?: ButtonBlockProps[] | null;
  trustItems?:
    | {
        /**
         * e.g. "📍 Kragujevac" — include the emoji in the text.
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Up to 3 images, pinned/rotated like polaroids. First image is the large one.
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image' | 'video') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    /**
     * Plays muted, looped, and autoplaying — no sound controls.
     */
    video?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlockProps".
 */
export interface ServicesBlockProps {
  eyebrow?: string | null;
  title: string;
  /**
   * Optional — rendered on its own line.
   */
  titleLine2?: string | null;
  items?:
    | {
        hasIcon?: boolean | null;
        iconType?: ('picker' | 'customSvg') | null;
        icon?: string | null;
        customSvg?: (number | null) | Media;
        iconPosition?: ('left' | 'right') | null;
        title: string;
        description?: string | null;
        /**
         * e.g. "od 1600 RSD" or "po dogovoru"
         */
        price?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image' | 'video') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    /**
     * Plays muted, looped, and autoplaying — no sound controls.
     */
    video?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'services';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessBlockProps".
 */
export interface ProcessBlockProps {
  eyebrow?: string | null;
  title: string;
  /**
   * Optional — rendered on its own line.
   */
  titleLine2?: string | null;
  /**
   * Step numbers (01, 02, ...) are generated automatically from order.
   */
  steps?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image' | 'video') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    /**
     * Plays muted, looped, and autoplaying — no sound controls.
     */
    video?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'process';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlockProps".
 */
export interface GalleryBlockProps {
  eyebrow?: string | null;
  title: string;
  description?: string | null;
  /**
   * Label for the filter button that shows every item.
   */
  allLabel?: string | null;
  /**
   * Leave empty to hide the filter bar and show all items.
   */
  categories?:
    | {
        label: string;
        /**
         * Matched against each item's Category field below.
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Items shown before the "Show all" button appears. Applies per filter too.
   */
  initialCount?: number | null;
  showAllLabel?: string | null;
  showLessLabel?: string | null;
  items?:
    | {
        image: number | Media;
        /**
         * A category "value" above. Leave blank to always show.
         */
        category?: string | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image' | 'video') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    /**
     * Plays muted, looped, and autoplaying — no sound controls.
     */
    video?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InstagramStripBlockProps".
 */
export interface InstagramStripBlockProps {
  eyebrow?: string | null;
  title: string;
  description?: string | null;
  /**
   * e.g. @nails.js_ — used on the fallback button before the feed is connected.
   */
  instagramHandle?: string | null;
  instagramUrl: string;
  /**
   * ID from your Elfsight "Instagram Feed" widget embed code (the part after "elfsight-app-"). Create the widget at elfsight.com, connect the Instagram account, limit it to 5 posts, and turn on its Header option so the live follower count + Follow button render inside the widget. Leave empty to show a static fallback button instead.
   */
  elfsightWidgetId?: string | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image' | 'video') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    /**
     * Plays muted, looped, and autoplaying — no sound controls.
     */
    video?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'instagramStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlockProps".
 */
export interface ContactBlockProps {
  eyebrow?: string | null;
  title: string;
  items?:
    | {
        /**
         * e.g. 📍
         */
        icon?: string | null;
        /**
         * First line, e.g. "Pozovi ili piši"
         */
        label: string;
        /**
         * Second line, e.g. "061 687 8225"
         */
        value: string;
        /**
         * If set, the Value is rendered as a link (tel:, mailto:, https://…).
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  card?: {
    /**
     * e.g. "Vidimo se uskoro 🩷"
     */
    scriptText?: string | null;
    text?: string | null;
    button?: ButtonBlockProps[] | null;
  };
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image' | 'video') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    /**
     * Plays muted, looped, and autoplaying — no sound controls.
     */
    video?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NavbarBlockProps".
 */
export interface NavbarBlockProps {
  /**
   * Optional — round brand mark shown next to the name.
   */
  logo?: (number | null) | Media;
  brandName: string;
  /**
   * e.g. "NAILS · KRAGUJEVAC"
   */
  brandSub?: string | null;
  /**
   * Select a menu from the Menus collection. Rendered flat (top-level items only) as the desktop links and inside the mobile full-screen menu.
   */
  menu: number | Menu;
  /**
   * Shown on desktop next to the links, and inside the mobile menu.
   */
  cta?: ButtonBlockProps[] | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'navbar';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterColumnsBlockProps".
 */
export interface FooterColumnsBlockProps {
  /**
   * Optional — round brand mark next to the name.
   */
  logo?: (number | null) | Media;
  brandName: string;
  /**
   * e.g. "NAILS · KRAGUJEVAC"
   */
  brandSub?: string | null;
  description?: string | null;
  social?:
    | {
        /**
         * e.g. 📍
         */
        icon: string;
        /**
         * Full URL, or mailto:/tel: for email and phone.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  columns?:
    | {
        /**
         * e.g. "Navigacija"
         */
        heading: string;
        links?:
          | {
              label: string;
              /**
               * Anchor (#usluge), tel:, mailto:, or full URL.
               */
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "© 2026 Jovana Simović Nails. Sva prava zadržana."
   */
  bottomText?: string | null;
  /**
   * Optional — e.g. a design credit.
   */
  bottomSecondaryText?: string | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'footerColumns';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlockProps".
 */
export interface AboutBlockProps {
  image: number | Media;
  eyebrow?: string | null;
  title: string;
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  facts?:
    | {
        /**
         * e.g. "📍 Kragujevac" — include the emoji in the text.
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  imagePosition?: ('left' | 'right') | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image' | 'video') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    /**
     * Plays muted, looped, and autoplaying — no sound controls.
     */
    video?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'about';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlockProps".
 */
export interface PricingBlockProps {
  title?: string | null;
  subtitle?: string | null;
  priceBlocks?:
    | {
        /**
         * e.g. "IZLIVANJE"
         */
        heading: string;
        /**
         * For long lists of add-ons/surcharges.
         */
        smallRows?: boolean | null;
        rows?:
          | {
              label: string;
              /**
               * e.g. "1600 RSD"
               */
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  note?: string | null;
  button: {
    text: string;
    linkType?: ('internal' | 'external') | null;
    internalLink?: (number | null) | Page;
    externalUrl?: string | null;
    newTab?: boolean | null;
    variant?: ('primary' | 'secondary' | 'ghost' | 'outline') | null;
    hasIcon?: boolean | null;
    iconType?: ('picker' | 'customSvg') | null;
    icon?: string | null;
    customSvg?: (number | null) | Media;
    iconPosition?: ('left' | 'right') | null;
    /**
     * Optional — custom ID / anchor
     */
    htmlId?: string | null;
    /**
     * Optional — extra class name(s) for custom styling
     */
    customClassName?: string | null;
  };
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image' | 'video') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    /**
     * Plays muted, looped, and autoplaying — no sound controls.
     */
    video?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlockProps".
 */
export interface FAQBlockProps {
  eyebrow?: string | null;
  title?: string | null;
  items?:
    | {
        question: string;
        answer: string;
        defaultOpen?: boolean | null;
        id?: string | null;
      }[]
    | null;
  allowMultiple?: boolean | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image' | 'video') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    /**
     * Plays muted, looped, and autoplaying — no sound controls.
     */
    video?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlockProps".
 */
export interface TestimonialsBlockProps {
  eyebrow?: string | null;
  title?: string | null;
  items?:
    | {
        quote: string;
        /**
         * Stars, 1–5.
         */
        rating?: number | null;
        name: string;
        role?: string | null;
        avatar?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  layout?: ('grid' | 'carousel') | null;
  columns?: ('col-2' | 'col-3') | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image' | 'video') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    /**
     * Plays muted, looped, and autoplaying — no sound controls.
     */
    video?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlockProps".
 */
export interface StatsBlockProps {
  items?:
    | {
        /**
         * e.g. 500+, 99%, 24/7
         */
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  columns?: ('col-2' | 'col-3' | 'col-4') | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image' | 'video') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    /**
     * Plays muted, looped, and autoplaying — no sound controls.
     */
    video?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamBlockProps".
 */
export interface TeamBlockProps {
  items?:
    | {
        photo?: (number | null) | Media;
        name: string;
        role?: string | null;
        bio?: string | null;
        socialLinks?:
          | {
              platform?: ('link' | 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'xTwitter' | 'whatsapp') | null;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  columns?: ('col-1' | 'col-2' | 'col-3' | 'col-4') | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  layout?: ('block' | 'flex' | 'grid') | null;
  verticalAlignment?: ('top' | 'middle' | 'bottom') | null;
  flexVariant?: ('row' | 'row-reverse' | 'row-wrap' | 'column' | 'column-reverse' | 'column-center') | null;
  gridVariant?: ('auto' | 'col-2' | 'col-3' | 'col-4') | null;
  gap?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image' | 'video') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    /**
     * Plays muted, looped, and autoplaying — no sound controls.
     */
    video?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'team';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlockProps".
 */
export interface FormBlockProps {
  form: number | Form;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image' | 'video') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    /**
     * Plays muted, looped, and autoplaying — no sound controls.
     */
    video?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DividerBlockProps".
 */
export interface DividerBlockProps {
  lineStyle?: ('solid' | 'dashed' | 'dotted') | null;
  thickness?: ('thin' | 'medium' | 'thick') | null;
  colorTheme?: string | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'divider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostsBlockProps".
 */
export interface PostsBlockProps {
  /**
   * Optional — section title above the posts loop
   */
  title?: string | null;
  populateBy?: ('latest' | 'categories' | 'manual') | null;
  /**
   * Maximum number of posts to fetch
   */
  limit: number;
  /**
   * Manually select which category/categries to display
   */
  selectedCategories?: (number | Category)[] | null;
  /**
   * Manually select which posts to display
   */
  selectedPosts?: (number | Post)[] | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  layout?: ('grid' | 'slider') | null;
  gap?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  gridColumns?: ('col-2' | 'col-3' | 'col-4') | null;
  autoplay?: boolean | null;
  showArrows?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'postsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  layout?: SectionBlockProps[] | null;
  /**
   * The primary image for this post.
   */
  featuredImage?: (number | null) | Media;
  /**
   * A short summary of the post used for previews.
   */
  excerpt?: string | null;
  category?: (number | Category)[] | null;
  /**
   * Title tag appearing in Google results (recommended up to 60 characters).
   */
  seoTitle?: string | null;
  /**
   * Meta description for search engines (recommended up to 160 characters).
   */
  seoDescription?: string | null;
  /**
   * Social media share image.
   */
  seoImage?: (number | null) | Media;
  /**
   * Only lowercase letters, numbers, and hyphens are allowed. Leaving it blank will automatically generate it from the title.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'menus';
        value: number | Menu;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        section?: T | SectionBlockPropsSelect<T>;
      };
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionBlockProps_select".
 */
export interface SectionBlockPropsSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        blockHolder0?: T | BlockHolderLevel0BlockPropsSelect<T>;
        postsBlock?: T | PostsBlockPropsSelect<T>;
      };
  settings?:
    | T
    | {
        htmlId?: T;
        customClassName?: T;
        viewport?: T;
        widthType?: T;
        alignment?: T;
        containerType?: T;
        spacing?:
          | T
          | {
              paddingTop?: T;
              paddingBottom?: T;
              marginTop?: T;
              marginBottom?: T;
            };
        background?:
          | T
          | {
              type?: T;
              colorTheme?: T;
              gradientTheme?: T;
              image?: T;
              video?: T;
              overlay?:
                | T
                | {
                    enabled?: T;
                    color?: T;
                    opacity?: T;
                  };
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockHolderLevel0BlockProps_select".
 */
export interface BlockHolderLevel0BlockPropsSelect<T extends boolean = true> {
  atoms?:
    | T
    | {
        blockHolder1?: T | BlockHolderLevel1BlockPropsSelect<T>;
        menu?: T | MenuBlockPropsSelect<T>;
        heading?: T | HeadingBlockPropsSelect<T>;
        richText?: T | RichTextBlockPropsSelect<T>;
        image?: T | ImageBlockPropsSelect<T>;
        video?: T | VideoBlockPropsSelect<T>;
        button?: T | ButtonBlockPropsSelect<T>;
        tabs?: T | TabsBlockPropsSelect<T>;
        slider?: T | SliderBlockPropsSelect<T>;
        accordion?: T | AccordionBlockPropsSelect<T>;
        cta?: T | CTABlockPropsSelect<T>;
        hero?: T | HeroBlockPropsSelect<T>;
        services?: T | ServicesBlockPropsSelect<T>;
        process?: T | ProcessBlockPropsSelect<T>;
        gallery?: T | GalleryBlockPropsSelect<T>;
        instagramStrip?: T | InstagramStripBlockPropsSelect<T>;
        contact?: T | ContactBlockPropsSelect<T>;
        navbar?: T | NavbarBlockPropsSelect<T>;
        footerColumns?: T | FooterColumnsBlockPropsSelect<T>;
        about?: T | AboutBlockPropsSelect<T>;
        pricing?: T | PricingBlockPropsSelect<T>;
        faq?: T | FAQBlockPropsSelect<T>;
        testimonials?: T | TestimonialsBlockPropsSelect<T>;
        stats?: T | StatsBlockPropsSelect<T>;
        team?: T | TeamBlockPropsSelect<T>;
        formBlock?: T | FormBlockPropsSelect<T>;
        divider?: T | DividerBlockPropsSelect<T>;
      };
  htmlId?: T;
  customClassName?: T;
  layout?: T;
  verticalAlignment?: T;
  flexVariant?: T;
  gridVariant?: T;
  gap?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockHolderLevel1BlockProps_select".
 */
export interface BlockHolderLevel1BlockPropsSelect<T extends boolean = true> {
  atoms?:
    | T
    | {
        blockHolder2?: T | BlockHolderLevel2BlockPropsSelect<T>;
        menu?: T | MenuBlockPropsSelect<T>;
        heading?: T | HeadingBlockPropsSelect<T>;
        richText?: T | RichTextBlockPropsSelect<T>;
        image?: T | ImageBlockPropsSelect<T>;
        video?: T | VideoBlockPropsSelect<T>;
        button?: T | ButtonBlockPropsSelect<T>;
        tabs?: T | TabsBlockPropsSelect<T>;
        slider?: T | SliderBlockPropsSelect<T>;
        accordion?: T | AccordionBlockPropsSelect<T>;
        cta?: T | CTABlockPropsSelect<T>;
        hero?: T | HeroBlockPropsSelect<T>;
        services?: T | ServicesBlockPropsSelect<T>;
        process?: T | ProcessBlockPropsSelect<T>;
        gallery?: T | GalleryBlockPropsSelect<T>;
        instagramStrip?: T | InstagramStripBlockPropsSelect<T>;
        contact?: T | ContactBlockPropsSelect<T>;
        navbar?: T | NavbarBlockPropsSelect<T>;
        footerColumns?: T | FooterColumnsBlockPropsSelect<T>;
        about?: T | AboutBlockPropsSelect<T>;
        pricing?: T | PricingBlockPropsSelect<T>;
        faq?: T | FAQBlockPropsSelect<T>;
        testimonials?: T | TestimonialsBlockPropsSelect<T>;
        stats?: T | StatsBlockPropsSelect<T>;
        team?: T | TeamBlockPropsSelect<T>;
        formBlock?: T | FormBlockPropsSelect<T>;
        divider?: T | DividerBlockPropsSelect<T>;
      };
  htmlId?: T;
  customClassName?: T;
  layout?: T;
  verticalAlignment?: T;
  flexVariant?: T;
  gridVariant?: T;
  gap?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockHolderLevel2BlockProps_select".
 */
export interface BlockHolderLevel2BlockPropsSelect<T extends boolean = true> {
  atoms?:
    | T
    | {
        menu?: T | MenuBlockPropsSelect<T>;
        heading?: T | HeadingBlockPropsSelect<T>;
        richText?: T | RichTextBlockPropsSelect<T>;
        image?: T | ImageBlockPropsSelect<T>;
        video?: T | VideoBlockPropsSelect<T>;
        button?: T | ButtonBlockPropsSelect<T>;
        tabs?: T | TabsBlockPropsSelect<T>;
        slider?: T | SliderBlockPropsSelect<T>;
        accordion?: T | AccordionBlockPropsSelect<T>;
        cta?: T | CTABlockPropsSelect<T>;
        hero?: T | HeroBlockPropsSelect<T>;
        services?: T | ServicesBlockPropsSelect<T>;
        process?: T | ProcessBlockPropsSelect<T>;
        gallery?: T | GalleryBlockPropsSelect<T>;
        instagramStrip?: T | InstagramStripBlockPropsSelect<T>;
        contact?: T | ContactBlockPropsSelect<T>;
        navbar?: T | NavbarBlockPropsSelect<T>;
        footerColumns?: T | FooterColumnsBlockPropsSelect<T>;
        about?: T | AboutBlockPropsSelect<T>;
        pricing?: T | PricingBlockPropsSelect<T>;
        faq?: T | FAQBlockPropsSelect<T>;
        testimonials?: T | TestimonialsBlockPropsSelect<T>;
        stats?: T | StatsBlockPropsSelect<T>;
        team?: T | TeamBlockPropsSelect<T>;
        formBlock?: T | FormBlockPropsSelect<T>;
        divider?: T | DividerBlockPropsSelect<T>;
      };
  htmlId?: T;
  customClassName?: T;
  layout?: T;
  verticalAlignment?: T;
  flexVariant?: T;
  gridVariant?: T;
  gap?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MenuBlockProps_select".
 */
export interface MenuBlockPropsSelect<T extends boolean = true> {
  menu?: T;
  orientation?: T;
  variant?: T;
  htmlId?: T;
  customClassName?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeadingBlockProps_select".
 */
export interface HeadingBlockPropsSelect<T extends boolean = true> {
  title?: T;
  variant?: T;
  titleTag?: T;
  color?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlockProps_select".
 */
export interface RichTextBlockPropsSelect<T extends boolean = true> {
  text?: T;
  variant?: T;
  color?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlockProps_select".
 */
export interface ImageBlockPropsSelect<T extends boolean = true> {
  image?: T;
  linkType?: T;
  internalLink?: T;
  externalUrl?: T;
  newTab?: T;
  aspectRatio?: T;
  customAspectRatio?: T;
  overlay?:
    | T
    | {
        enabled?: T;
        color?: T;
        opacity?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlockProps_select".
 */
export interface VideoBlockPropsSelect<T extends boolean = true> {
  sourceType?: T;
  file?: T;
  poster?: T;
  url?: T;
  aspectRatio?: T;
  customAspectRatio?: T;
  controls?: T;
  autoplay?: T;
  loop?: T;
  muted?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonBlockProps_select".
 */
export interface ButtonBlockPropsSelect<T extends boolean = true> {
  text?: T;
  linkType?: T;
  internalLink?: T;
  externalUrl?: T;
  newTab?: T;
  variant?: T;
  hasIcon?: T;
  iconType?: T;
  icon?: T;
  customSvg?: T;
  iconPosition?: T;
  htmlId?: T;
  customClassName?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabsBlockProps_select".
 */
export interface TabsBlockPropsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        blocks?:
          | T
          | {
              heading?: T | HeadingBlockPropsSelect<T>;
              richText?: T | RichTextBlockPropsSelect<T>;
              image?: T | ImageBlockPropsSelect<T>;
              button?: T | ButtonBlockPropsSelect<T>;
            };
        label?: T;
        defaultActive?: T;
        hasIcon?: T;
        iconType?: T;
        icon?: T;
        customSvg?: T;
        iconPosition?: T;
        id?: T;
      };
  orientation?: T;
  variant?: T;
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SliderBlockProps_select".
 */
export interface SliderBlockPropsSelect<T extends boolean = true> {
  settings?:
    | T
    | {
        orientation?: T;
        spaceBetween?: T;
        slidesPerView?: T;
      };
  slides?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        video?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlockProps_select".
 */
export interface AccordionBlockPropsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        blocks?:
          | T
          | {
              heading?: T | HeadingBlockPropsSelect<T>;
              richText?: T | RichTextBlockPropsSelect<T>;
              image?: T | ImageBlockPropsSelect<T>;
              button?: T | ButtonBlockPropsSelect<T>;
            };
        label?: T;
        defaultOpen?: T;
        hasIcon?: T;
        iconType?: T;
        icon?: T;
        customSvg?: T;
        iconPosition?: T;
        id?: T;
      };
  allowMultiple?: T;
  variant?: T;
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        video?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlockProps_select".
 */
export interface CTABlockPropsSelect<T extends boolean = true> {
  title?: T;
  text?: T;
  buttons?:
    | T
    | {
        button?: T | ButtonBlockPropsSelect<T>;
      };
  alignment?: T;
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        video?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlockProps_select".
 */
export interface HeroBlockPropsSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  highlightedTitle?: T;
  description?: T;
  buttons?:
    | T
    | {
        button?: T | ButtonBlockPropsSelect<T>;
      };
  trustItems?:
    | T
    | {
        label?: T;
        id?: T;
      };
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        video?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlockProps_select".
 */
export interface ServicesBlockPropsSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  titleLine2?: T;
  items?:
    | T
    | {
        hasIcon?: T;
        iconType?: T;
        icon?: T;
        customSvg?: T;
        iconPosition?: T;
        title?: T;
        description?: T;
        price?: T;
        id?: T;
      };
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        video?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessBlockProps_select".
 */
export interface ProcessBlockPropsSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  titleLine2?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        video?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlockProps_select".
 */
export interface GalleryBlockPropsSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  allLabel?: T;
  categories?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  initialCount?: T;
  showAllLabel?: T;
  showLessLabel?: T;
  items?:
    | T
    | {
        image?: T;
        category?: T;
        caption?: T;
        id?: T;
      };
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        video?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InstagramStripBlockProps_select".
 */
export interface InstagramStripBlockPropsSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  instagramHandle?: T;
  instagramUrl?: T;
  elfsightWidgetId?: T;
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        video?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlockProps_select".
 */
export interface ContactBlockPropsSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  items?:
    | T
    | {
        icon?: T;
        label?: T;
        value?: T;
        url?: T;
        id?: T;
      };
  card?:
    | T
    | {
        scriptText?: T;
        text?: T;
        button?:
          | T
          | {
              button?: T | ButtonBlockPropsSelect<T>;
            };
      };
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        video?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NavbarBlockProps_select".
 */
export interface NavbarBlockPropsSelect<T extends boolean = true> {
  logo?: T;
  brandName?: T;
  brandSub?: T;
  menu?: T;
  cta?:
    | T
    | {
        button?: T | ButtonBlockPropsSelect<T>;
      };
  htmlId?: T;
  customClassName?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterColumnsBlockProps_select".
 */
export interface FooterColumnsBlockPropsSelect<T extends boolean = true> {
  logo?: T;
  brandName?: T;
  brandSub?: T;
  description?: T;
  social?:
    | T
    | {
        icon?: T;
        url?: T;
        id?: T;
      };
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  bottomText?: T;
  bottomSecondaryText?: T;
  htmlId?: T;
  customClassName?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlockProps_select".
 */
export interface AboutBlockPropsSelect<T extends boolean = true> {
  image?: T;
  eyebrow?: T;
  title?: T;
  text?: T;
  facts?:
    | T
    | {
        label?: T;
        id?: T;
      };
  imagePosition?: T;
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        video?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlockProps_select".
 */
export interface PricingBlockPropsSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  priceBlocks?:
    | T
    | {
        heading?: T;
        smallRows?: T;
        rows?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  note?: T;
  button?:
    | T
    | {
        text?: T;
        linkType?: T;
        internalLink?: T;
        externalUrl?: T;
        newTab?: T;
        variant?: T;
        hasIcon?: T;
        iconType?: T;
        icon?: T;
        customSvg?: T;
        iconPosition?: T;
        htmlId?: T;
        customClassName?: T;
      };
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        video?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlockProps_select".
 */
export interface FAQBlockPropsSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        defaultOpen?: T;
        id?: T;
      };
  allowMultiple?: T;
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        video?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlockProps_select".
 */
export interface TestimonialsBlockPropsSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  items?:
    | T
    | {
        quote?: T;
        rating?: T;
        name?: T;
        role?: T;
        avatar?: T;
        id?: T;
      };
  layout?: T;
  columns?: T;
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        video?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlockProps_select".
 */
export interface StatsBlockPropsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  columns?: T;
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        video?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamBlockProps_select".
 */
export interface TeamBlockPropsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        photo?: T;
        name?: T;
        role?: T;
        bio?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  columns?: T;
  htmlId?: T;
  customClassName?: T;
  layout?: T;
  verticalAlignment?: T;
  flexVariant?: T;
  gridVariant?: T;
  gap?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        video?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlockProps_select".
 */
export interface FormBlockPropsSelect<T extends boolean = true> {
  form?: T;
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        video?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DividerBlockProps_select".
 */
export interface DividerBlockPropsSelect<T extends boolean = true> {
  lineStyle?: T;
  thickness?: T;
  colorTheme?: T;
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostsBlockProps_select".
 */
export interface PostsBlockPropsSelect<T extends boolean = true> {
  title?: T;
  populateBy?: T;
  limit?: T;
  selectedCategories?: T;
  selectedPosts?: T;
  htmlId?: T;
  customClassName?: T;
  layout?: T;
  gap?: T;
  gridColumns?: T;
  autoplay?: T;
  showArrows?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        section?: T | SectionBlockPropsSelect<T>;
      };
  featuredImage?: T;
  excerpt?: T;
  category?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  name?: T;
  items?:
    | T
    | {
        page?: T;
        anchor?: T;
        url?: T;
        label?: T;
        type?: T;
        newTab?: T;
        children?:
          | T
          | {
              page?: T;
              anchor?: T;
              url?: T;
              label?: T;
              type?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  orientation?: T;
  variant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors".
 */
export interface Color {
  id: number;
  colors?:
    | {
        label: string;
        /**
         * It will be used as a CSS class/variable — without spaces
         */
        value: string;
        hex?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  blocks?:
    | (
        | SectionBlockProps
        | BlockHolderLevel0BlockProps
        | MenuBlockProps
        | HeadingBlockProps
        | RichTextBlockProps
        | ImageBlockProps
        | VideoBlockProps
        | ButtonBlockProps
        | TabsBlockProps
        | SliderBlockProps
        | AccordionBlockProps
        | CTABlockProps
        | HeroBlockProps
        | ServicesBlockProps
        | ProcessBlockProps
        | GalleryBlockProps
        | InstagramStripBlockProps
        | ContactBlockProps
        | NavbarBlockProps
        | FooterColumnsBlockProps
        | AboutBlockProps
        | PricingBlockProps
        | FAQBlockProps
        | TestimonialsBlockProps
        | StatsBlockProps
        | TeamBlockProps
        | FormBlockProps
        | DividerBlockProps
      )[]
    | null;
  variant?: ('default' | 'transparent' | 'minimal') | null;
  sticky?: ('none' | 'sticky' | 'sticky-up') | null;
  /**
   * Header background color (applied at ~86% opacity, with blur).
   */
  colorTheme?: string | null;
  /**
   * Optional — custom ID attribute on the header element
   */
  htmlId?: string | null;
  paddingTop?: number | null;
  paddingBottom?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  blocks?:
    | (
        | SectionBlockProps
        | BlockHolderLevel0BlockProps
        | MenuBlockProps
        | HeadingBlockProps
        | RichTextBlockProps
        | ImageBlockProps
        | VideoBlockProps
        | ButtonBlockProps
        | TabsBlockProps
        | SliderBlockProps
        | AccordionBlockProps
        | CTABlockProps
        | HeroBlockProps
        | ServicesBlockProps
        | ProcessBlockProps
        | GalleryBlockProps
        | InstagramStripBlockProps
        | ContactBlockProps
        | NavbarBlockProps
        | FooterColumnsBlockProps
        | AboutBlockProps
        | PricingBlockProps
        | FAQBlockProps
        | TestimonialsBlockProps
        | StatsBlockProps
        | TeamBlockProps
        | FormBlockProps
        | DividerBlockProps
      )[]
    | null;
  variant?: ('default' | 'minimal') | null;
  /**
   * Optional — custom ID attribute on the footer element
   */
  htmlId?: string | null;
  /**
   * Footer background color. Leave empty for a transparent background.
   */
  colorTheme?: string | null;
  paddingTop?: number | null;
  paddingBottom?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Used in browser tab, SEO fallback, and logo alt text
   */
  siteTitle: string;
  /**
   * Short description — used in default SEO if no meta description is set
   */
  tagline?: string | null;
  /**
   * Displayed in header — recommended SVG or PNG with transparency
   */
  logo?: (number | null) | Media;
  /**
   * Optional — used when header is on dark background
   */
  logoDark?: (number | null) | Media;
  /**
   * Fiksna traka na dnu ekrana, vidljiva samo na mobilnim uređajima (≤640px), sa dugmićima za DM i poziv
   */
  mobileCtaEnabled?: boolean | null;
  /**
   * Boja pozadine trake. Ostavi prazno za podrazumevanu (blush soft).
   */
  colorTheme?: string | null;
  instagramUrl?: string | null;
  instagramLabel?: string | null;
  phone?: string | null;
  phoneLabel?: string | null;
  /**
   * ICO, PNG ili SVG — preporučeno 32×32px ili 512×512px
   */
  favicon?: (number | null) | Media;
  /**
   * PNG, 180×180px — koristi se na iOS home screen
   */
  appleTouchIcon?: (number | null) | Media;
  /**
   * Fallback vrijednosti kada stranica nema custom SEO
   */
  defaultMeta?: {
    /**
     * Ako je prazno, koristi Site Title
     */
    title?: string | null;
    /**
     * Preporučeno: 120–160 karaktera
     */
    description?: string | null;
    /**
     * Za social sharing — preporučeno 1200×630px
     */
    ogImage?: (number | null) | Media;
  };
  /**
   * Koristi %s za naziv stranice, %site za naziv sajta
   */
  titleTemplate?: string | null;
  robots?: ('index, follow' | 'noindex, nofollow' | 'index, nofollow' | 'noindex, follow') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors_select".
 */
export interface ColorsSelect<T extends boolean = true> {
  colors?:
    | T
    | {
        label?: T;
        value?: T;
        hex?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        section?: T | SectionBlockPropsSelect<T>;
        blockHolder0?: T | BlockHolderLevel0BlockPropsSelect<T>;
        menu?: T | MenuBlockPropsSelect<T>;
        heading?: T | HeadingBlockPropsSelect<T>;
        richText?: T | RichTextBlockPropsSelect<T>;
        image?: T | ImageBlockPropsSelect<T>;
        video?: T | VideoBlockPropsSelect<T>;
        button?: T | ButtonBlockPropsSelect<T>;
        tabs?: T | TabsBlockPropsSelect<T>;
        slider?: T | SliderBlockPropsSelect<T>;
        accordion?: T | AccordionBlockPropsSelect<T>;
        cta?: T | CTABlockPropsSelect<T>;
        hero?: T | HeroBlockPropsSelect<T>;
        services?: T | ServicesBlockPropsSelect<T>;
        process?: T | ProcessBlockPropsSelect<T>;
        gallery?: T | GalleryBlockPropsSelect<T>;
        instagramStrip?: T | InstagramStripBlockPropsSelect<T>;
        contact?: T | ContactBlockPropsSelect<T>;
        navbar?: T | NavbarBlockPropsSelect<T>;
        footerColumns?: T | FooterColumnsBlockPropsSelect<T>;
        about?: T | AboutBlockPropsSelect<T>;
        pricing?: T | PricingBlockPropsSelect<T>;
        faq?: T | FAQBlockPropsSelect<T>;
        testimonials?: T | TestimonialsBlockPropsSelect<T>;
        stats?: T | StatsBlockPropsSelect<T>;
        team?: T | TeamBlockPropsSelect<T>;
        formBlock?: T | FormBlockPropsSelect<T>;
        divider?: T | DividerBlockPropsSelect<T>;
      };
  variant?: T;
  sticky?: T;
  colorTheme?: T;
  htmlId?: T;
  paddingTop?: T;
  paddingBottom?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        section?: T | SectionBlockPropsSelect<T>;
        blockHolder0?: T | BlockHolderLevel0BlockPropsSelect<T>;
        menu?: T | MenuBlockPropsSelect<T>;
        heading?: T | HeadingBlockPropsSelect<T>;
        richText?: T | RichTextBlockPropsSelect<T>;
        image?: T | ImageBlockPropsSelect<T>;
        video?: T | VideoBlockPropsSelect<T>;
        button?: T | ButtonBlockPropsSelect<T>;
        tabs?: T | TabsBlockPropsSelect<T>;
        slider?: T | SliderBlockPropsSelect<T>;
        accordion?: T | AccordionBlockPropsSelect<T>;
        cta?: T | CTABlockPropsSelect<T>;
        hero?: T | HeroBlockPropsSelect<T>;
        services?: T | ServicesBlockPropsSelect<T>;
        process?: T | ProcessBlockPropsSelect<T>;
        gallery?: T | GalleryBlockPropsSelect<T>;
        instagramStrip?: T | InstagramStripBlockPropsSelect<T>;
        contact?: T | ContactBlockPropsSelect<T>;
        navbar?: T | NavbarBlockPropsSelect<T>;
        footerColumns?: T | FooterColumnsBlockPropsSelect<T>;
        about?: T | AboutBlockPropsSelect<T>;
        pricing?: T | PricingBlockPropsSelect<T>;
        faq?: T | FAQBlockPropsSelect<T>;
        testimonials?: T | TestimonialsBlockPropsSelect<T>;
        stats?: T | StatsBlockPropsSelect<T>;
        team?: T | TeamBlockPropsSelect<T>;
        formBlock?: T | FormBlockPropsSelect<T>;
        divider?: T | DividerBlockPropsSelect<T>;
      };
  variant?: T;
  htmlId?: T;
  colorTheme?: T;
  paddingTop?: T;
  paddingBottom?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  tagline?: T;
  logo?: T;
  logoDark?: T;
  mobileCtaEnabled?: T;
  colorTheme?: T;
  instagramUrl?: T;
  instagramLabel?: T;
  phone?: T;
  phoneLabel?: T;
  favicon?: T;
  appleTouchIcon?: T;
  defaultMeta?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  titleTemplate?: T;
  robots?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}