/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    menus: Menu;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    colors: Color;
    header: Header;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    colors: ColorsSelect<false> | ColorsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  layout?: SectionBlockProps[] | null;
  /**
   * Title tag appearing in Google results (recommended up to 60 characters).
   */
  seoTitle?: string | null;
  /**
   * Meta description for search engines (recommended up to 160 characters).
   */
  seoDescription?: string | null;
  /**
   * Social media share image.
   */
  seoImage?: (number | null) | Media;
  /**
   * Only lowercase letters, numbers, and hyphens are allowed. Leaving it blank will automatically generate it from the title.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionBlockProps".
 */
export interface SectionBlockProps {
  blocks?: (BlockHolderLevel0BlockProps | PostsBlockProps)[] | null;
  settings?: {
    /**
     * Optional — custom ID / anchor
     */
    htmlId?: string | null;
    /**
     * Optional — extra class name(s) for custom styling
     */
    customClassName?: string | null;
    viewport?: ('auto' | 'full') | null;
    widthType?: ('fullWidth' | 'boxed') | null;
    /**
     * Optional — vertical alignment
     */
    alignment?: ('top' | 'center' | 'bottom') | null;
    containerType?: ('container-xl' | 'container-lg' | 'container' | 'container-xs') | null;
    spacing?: {
      paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
      paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
      marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
      marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    };
    background?: {
      type?: ('blank' | 'color' | 'gradient' | 'image') | null;
      colorTheme?: string | null;
      gradientTheme?: ('warm' | 'cool') | null;
      image?: (number | null) | Media;
      overlay?: {
        enabled?: boolean | null;
        color?: string | null;
        /**
         * 0 - 100
         */
        opacity?: number | null;
      };
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockHolderLevel0BlockProps".
 */
export interface BlockHolderLevel0BlockProps {
  atoms?:
    | (
        | BlockHolderLevel1BlockProps
        | MenuBlockProps
        | HeadingBlockProps
        | RichTextBlockProps
        | ImageBlockProps
        | ButtonBlockProps
        | TabsBlockProps
        | SliderBlockProps
        | AccordionBlockProps
        | CTABlockProps
        | TestimonialsBlockProps
        | StatsBlockProps
        | TeamBlockProps
      )[]
    | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  layout?: ('block' | 'flex' | 'grid') | null;
  verticalAlignment?: ('top' | 'middle' | 'bottom') | null;
  flexVariant?: ('row' | 'row-reverse' | 'row-wrap' | 'column' | 'column-reverse') | null;
  gridVariant?: ('auto' | 'col-2' | 'col-3') | null;
  gap?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blockHolder0';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockHolderLevel1BlockProps".
 */
export interface BlockHolderLevel1BlockProps {
  atoms?:
    | (
        | BlockHolderLevel2BlockProps
        | MenuBlockProps
        | HeadingBlockProps
        | RichTextBlockProps
        | ImageBlockProps
        | ButtonBlockProps
        | TabsBlockProps
        | SliderBlockProps
        | AccordionBlockProps
        | CTABlockProps
        | TestimonialsBlockProps
        | StatsBlockProps
        | TeamBlockProps
      )[]
    | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  layout?: ('block' | 'flex' | 'grid') | null;
  verticalAlignment?: ('top' | 'middle' | 'bottom') | null;
  flexVariant?: ('row' | 'row-reverse' | 'row-wrap' | 'column' | 'column-reverse') | null;
  gridVariant?: ('auto' | 'col-2' | 'col-3') | null;
  gap?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blockHolder1';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockHolderLevel2BlockProps".
 */
export interface BlockHolderLevel2BlockProps {
  atoms?:
    | (
        | MenuBlockProps
        | HeadingBlockProps
        | RichTextBlockProps
        | ImageBlockProps
        | ButtonBlockProps
        | TabsBlockProps
        | SliderBlockProps
        | AccordionBlockProps
        | CTABlockProps
        | TestimonialsBlockProps
        | StatsBlockProps
        | TeamBlockProps
      )[]
    | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  layout?: ('block' | 'flex' | 'grid') | null;
  verticalAlignment?: ('top' | 'middle' | 'bottom') | null;
  flexVariant?: ('row' | 'row-reverse' | 'row-wrap' | 'column' | 'column-reverse') | null;
  gridVariant?: ('auto' | 'col-2' | 'col-3') | null;
  gap?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blockHolder2';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MenuBlockProps".
 */
export interface MenuBlockProps {
  /**
   * Select a menu from the Menus collection
   */
  menu: number | Menu;
  orientation?: ('horizontal' | 'vertical') | null;
  variant?: ('default' | 'minimal' | 'pills') | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'menu';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: number;
  name: string;
  items?:
    | {
        /**
         * Select a page
         */
        page?: (number | null) | Page;
        /**
         * Optional — element ID on the page (without #)
         */
        anchor?: string | null;
        /**
         * Full URL (https://...)
         */
        url?: string | null;
        label?: string | null;
        type?: ('internal' | 'external') | null;
        newTab?: boolean | null;
        children?:
          | {
              page?: (number | null) | Page;
              anchor?: string | null;
              url?: string | null;
              label: string;
              type?: ('internal' | 'external') | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  orientation?: ('horizontal' | 'vertical') | null;
  variant?: 'default' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeadingBlockProps".
 */
export interface HeadingBlockProps {
  title?: string | null;
  variant?: ('default' | 'center' | 'right') | null;
  titleTag?: ('h1' | 'h2' | 'h3' | 'h4' | 'p' | 'span') | null;
  color?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heading';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlockProps".
 */
export interface RichTextBlockProps {
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  variant?: ('default' | 'center' | 'right') | null;
  color?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlockProps".
 */
export interface ImageBlockProps {
  image?: (number | null) | Media;
  linkType?: ('none' | 'internal' | 'external') | null;
  internalLink?: (number | null) | Page;
  externalUrl?: string | null;
  newTab?: boolean | null;
  aspectRatio?: ('auto' | '1/1' | '3/2' | '4/3' | '16/9' | '2/3' | '3/4' | '9/16' | 'custom') | null;
  /**
   * Format: 16/9, 4/3, 1/1...
   */
  customAspectRatio?: string | null;
  overlay?: {
    enabled?: boolean | null;
    color?: string | null;
    /**
     * 0 - 100
     */
    opacity?: number | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonBlockProps".
 */
export interface ButtonBlockProps {
  text: string;
  linkType?: ('internal' | 'external') | null;
  internalLink?: (number | null) | Page;
  externalUrl?: string | null;
  newTab?: boolean | null;
  variant?: ('primary' | 'secondary' | 'ghost' | 'outline') | null;
  hasIcon?: boolean | null;
  iconType?: ('picker' | 'customSvg') | null;
  icon?: string | null;
  customSvg?: (number | null) | Media;
  iconPosition?: ('left' | 'right') | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'button';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabsBlockProps".
 */
export interface TabsBlockProps {
  items?:
    | {
        blocks?: (HeadingBlockProps | RichTextBlockProps | ImageBlockProps | ButtonBlockProps)[] | null;
        label: string;
        defaultActive?: boolean | null;
        hasIcon?: boolean | null;
        iconType?: ('picker' | 'customSvg') | null;
        icon?: string | null;
        customSvg?: (number | null) | Media;
        iconPosition?: ('left' | 'right') | null;
        id?: string | null;
      }[]
    | null;
  orientation?: ('horizontal' | 'vertical') | null;
  variant?: ('default' | 'full' | 'minimal') | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'tabs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SliderBlockProps".
 */
export interface SliderBlockProps {
  settings?: {
    orientation?: ('horizontal' | 'vertical') | null;
    /**
     * Space between slides in px
     */
    spaceBetween?: number | null;
    slidesPerView?: number | null;
  };
  slides?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'slider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlockProps".
 */
export interface AccordionBlockProps {
  items?:
    | {
        blocks?: (HeadingBlockProps | RichTextBlockProps | ImageBlockProps | ButtonBlockProps)[] | null;
        label: string;
        defaultOpen?: boolean | null;
        hasIcon?: boolean | null;
        iconType?: ('picker' | 'customSvg') | null;
        icon?: string | null;
        customSvg?: (number | null) | Media;
        iconPosition?: ('left' | 'right') | null;
        id?: string | null;
      }[]
    | null;
  allowMultiple?: boolean | null;
  variant?: ('default' | 'bordered' | 'minimal') | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlockProps".
 */
export interface CTABlockProps {
  title: string;
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  buttons?: ButtonBlockProps[] | null;
  alignment?: ('left' | 'center') | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlockProps".
 */
export interface TestimonialsBlockProps {
  items?:
    | {
        quote: string;
        name: string;
        role?: string | null;
        avatar?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  layout?: ('grid' | 'carousel') | null;
  columns?: ('col-2' | 'col-3') | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlockProps".
 */
export interface StatsBlockProps {
  items?:
    | {
        /**
         * e.g. 500+, 99%, 24/7
         */
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  columns?: ('col-2' | 'col-3' | 'col-4') | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamBlockProps".
 */
export interface TeamBlockProps {
  items?:
    | {
        photo?: (number | null) | Media;
        name: string;
        role?: string | null;
        bio?: string | null;
        socialLinks?:
          | {
              platform?: ('link' | 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'xTwitter' | 'whatsapp') | null;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  columns?: ('col-2' | 'col-3' | 'col-4') | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  spacing?: {
    paddingTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    paddingBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginTop?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    marginBottom?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  background?: {
    type?: ('blank' | 'color' | 'gradient' | 'image') | null;
    colorTheme?: string | null;
    gradientTheme?: ('warm' | 'cool') | null;
    image?: (number | null) | Media;
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
      /**
       * 0 - 100
       */
      opacity?: number | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'team';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostsBlockProps".
 */
export interface PostsBlockProps {
  /**
   * Optional — section title above the posts loop
   */
  title?: string | null;
  populateBy?: ('latest' | 'categories' | 'manual') | null;
  /**
   * Maximum number of posts to fetch
   */
  limit: number;
  /**
   * Manually select which category/categries to display
   */
  selectedCategories?: (number | Category)[] | null;
  /**
   * Manually select which posts to display
   */
  selectedPosts?: (number | Post)[] | null;
  /**
   * Optional — custom ID / anchor
   */
  htmlId?: string | null;
  /**
   * Optional — extra class name(s) for custom styling
   */
  customClassName?: string | null;
  layout?: ('grid' | 'slider') | null;
  gap?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  gridColumns?: ('col-2' | 'col-3' | 'col-4') | null;
  autoplay?: boolean | null;
  showArrows?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'postsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  layout?: SectionBlockProps[] | null;
  /**
   * The primary image for this post.
   */
  featuredImage?: (number | null) | Media;
  /**
   * A short summary of the post used for previews.
   */
  excerpt?: string | null;
  category?: (number | Category)[] | null;
  /**
   * Title tag appearing in Google results (recommended up to 60 characters).
   */
  seoTitle?: string | null;
  /**
   * Meta description for search engines (recommended up to 160 characters).
   */
  seoDescription?: string | null;
  /**
   * Social media share image.
   */
  seoImage?: (number | null) | Media;
  /**
   * Only lowercase letters, numbers, and hyphens are allowed. Leaving it blank will automatically generate it from the title.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'menus';
        value: number | Menu;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        section?: T | SectionBlockPropsSelect<T>;
      };
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionBlockProps_select".
 */
export interface SectionBlockPropsSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        blockHolder0?: T | BlockHolderLevel0BlockPropsSelect<T>;
        postsBlock?: T | PostsBlockPropsSelect<T>;
      };
  settings?:
    | T
    | {
        htmlId?: T;
        customClassName?: T;
        viewport?: T;
        widthType?: T;
        alignment?: T;
        containerType?: T;
        spacing?:
          | T
          | {
              paddingTop?: T;
              paddingBottom?: T;
              marginTop?: T;
              marginBottom?: T;
            };
        background?:
          | T
          | {
              type?: T;
              colorTheme?: T;
              gradientTheme?: T;
              image?: T;
              overlay?:
                | T
                | {
                    enabled?: T;
                    color?: T;
                    opacity?: T;
                  };
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockHolderLevel0BlockProps_select".
 */
export interface BlockHolderLevel0BlockPropsSelect<T extends boolean = true> {
  atoms?:
    | T
    | {
        blockHolder1?: T | BlockHolderLevel1BlockPropsSelect<T>;
        menu?: T | MenuBlockPropsSelect<T>;
        heading?: T | HeadingBlockPropsSelect<T>;
        richText?: T | RichTextBlockPropsSelect<T>;
        image?: T | ImageBlockPropsSelect<T>;
        button?: T | ButtonBlockPropsSelect<T>;
        tabs?: T | TabsBlockPropsSelect<T>;
        slider?: T | SliderBlockPropsSelect<T>;
        accordion?: T | AccordionBlockPropsSelect<T>;
        cta?: T | CTABlockPropsSelect<T>;
        testimonials?: T | TestimonialsBlockPropsSelect<T>;
        stats?: T | StatsBlockPropsSelect<T>;
        team?: T | TeamBlockPropsSelect<T>;
      };
  htmlId?: T;
  customClassName?: T;
  layout?: T;
  verticalAlignment?: T;
  flexVariant?: T;
  gridVariant?: T;
  gap?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockHolderLevel1BlockProps_select".
 */
export interface BlockHolderLevel1BlockPropsSelect<T extends boolean = true> {
  atoms?:
    | T
    | {
        blockHolder2?: T | BlockHolderLevel2BlockPropsSelect<T>;
        menu?: T | MenuBlockPropsSelect<T>;
        heading?: T | HeadingBlockPropsSelect<T>;
        richText?: T | RichTextBlockPropsSelect<T>;
        image?: T | ImageBlockPropsSelect<T>;
        button?: T | ButtonBlockPropsSelect<T>;
        tabs?: T | TabsBlockPropsSelect<T>;
        slider?: T | SliderBlockPropsSelect<T>;
        accordion?: T | AccordionBlockPropsSelect<T>;
        cta?: T | CTABlockPropsSelect<T>;
        testimonials?: T | TestimonialsBlockPropsSelect<T>;
        stats?: T | StatsBlockPropsSelect<T>;
        team?: T | TeamBlockPropsSelect<T>;
      };
  htmlId?: T;
  customClassName?: T;
  layout?: T;
  verticalAlignment?: T;
  flexVariant?: T;
  gridVariant?: T;
  gap?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockHolderLevel2BlockProps_select".
 */
export interface BlockHolderLevel2BlockPropsSelect<T extends boolean = true> {
  atoms?:
    | T
    | {
        menu?: T | MenuBlockPropsSelect<T>;
        heading?: T | HeadingBlockPropsSelect<T>;
        richText?: T | RichTextBlockPropsSelect<T>;
        image?: T | ImageBlockPropsSelect<T>;
        button?: T | ButtonBlockPropsSelect<T>;
        tabs?: T | TabsBlockPropsSelect<T>;
        slider?: T | SliderBlockPropsSelect<T>;
        accordion?: T | AccordionBlockPropsSelect<T>;
        cta?: T | CTABlockPropsSelect<T>;
        testimonials?: T | TestimonialsBlockPropsSelect<T>;
        stats?: T | StatsBlockPropsSelect<T>;
        team?: T | TeamBlockPropsSelect<T>;
      };
  htmlId?: T;
  customClassName?: T;
  layout?: T;
  verticalAlignment?: T;
  flexVariant?: T;
  gridVariant?: T;
  gap?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MenuBlockProps_select".
 */
export interface MenuBlockPropsSelect<T extends boolean = true> {
  menu?: T;
  orientation?: T;
  variant?: T;
  htmlId?: T;
  customClassName?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeadingBlockProps_select".
 */
export interface HeadingBlockPropsSelect<T extends boolean = true> {
  title?: T;
  variant?: T;
  titleTag?: T;
  color?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlockProps_select".
 */
export interface RichTextBlockPropsSelect<T extends boolean = true> {
  text?: T;
  variant?: T;
  color?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlockProps_select".
 */
export interface ImageBlockPropsSelect<T extends boolean = true> {
  image?: T;
  linkType?: T;
  internalLink?: T;
  externalUrl?: T;
  newTab?: T;
  aspectRatio?: T;
  customAspectRatio?: T;
  overlay?:
    | T
    | {
        enabled?: T;
        color?: T;
        opacity?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonBlockProps_select".
 */
export interface ButtonBlockPropsSelect<T extends boolean = true> {
  text?: T;
  linkType?: T;
  internalLink?: T;
  externalUrl?: T;
  newTab?: T;
  variant?: T;
  hasIcon?: T;
  iconType?: T;
  icon?: T;
  customSvg?: T;
  iconPosition?: T;
  htmlId?: T;
  customClassName?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabsBlockProps_select".
 */
export interface TabsBlockPropsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        blocks?:
          | T
          | {
              heading?: T | HeadingBlockPropsSelect<T>;
              richText?: T | RichTextBlockPropsSelect<T>;
              image?: T | ImageBlockPropsSelect<T>;
              button?: T | ButtonBlockPropsSelect<T>;
            };
        label?: T;
        defaultActive?: T;
        hasIcon?: T;
        iconType?: T;
        icon?: T;
        customSvg?: T;
        iconPosition?: T;
        id?: T;
      };
  orientation?: T;
  variant?: T;
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SliderBlockProps_select".
 */
export interface SliderBlockPropsSelect<T extends boolean = true> {
  settings?:
    | T
    | {
        orientation?: T;
        spaceBetween?: T;
        slidesPerView?: T;
      };
  slides?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlockProps_select".
 */
export interface AccordionBlockPropsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        blocks?:
          | T
          | {
              heading?: T | HeadingBlockPropsSelect<T>;
              richText?: T | RichTextBlockPropsSelect<T>;
              image?: T | ImageBlockPropsSelect<T>;
              button?: T | ButtonBlockPropsSelect<T>;
            };
        label?: T;
        defaultOpen?: T;
        hasIcon?: T;
        iconType?: T;
        icon?: T;
        customSvg?: T;
        iconPosition?: T;
        id?: T;
      };
  allowMultiple?: T;
  variant?: T;
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlockProps_select".
 */
export interface CTABlockPropsSelect<T extends boolean = true> {
  title?: T;
  text?: T;
  buttons?:
    | T
    | {
        button?: T | ButtonBlockPropsSelect<T>;
      };
  alignment?: T;
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlockProps_select".
 */
export interface TestimonialsBlockPropsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        quote?: T;
        name?: T;
        role?: T;
        avatar?: T;
        id?: T;
      };
  layout?: T;
  columns?: T;
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlockProps_select".
 */
export interface StatsBlockPropsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  columns?: T;
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamBlockProps_select".
 */
export interface TeamBlockPropsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        photo?: T;
        name?: T;
        role?: T;
        bio?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  columns?: T;
  htmlId?: T;
  customClassName?: T;
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
      };
  background?:
    | T
    | {
        type?: T;
        colorTheme?: T;
        gradientTheme?: T;
        image?: T;
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
              opacity?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostsBlockProps_select".
 */
export interface PostsBlockPropsSelect<T extends boolean = true> {
  title?: T;
  populateBy?: T;
  limit?: T;
  selectedCategories?: T;
  selectedPosts?: T;
  htmlId?: T;
  customClassName?: T;
  layout?: T;
  gap?: T;
  gridColumns?: T;
  autoplay?: T;
  showArrows?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        section?: T | SectionBlockPropsSelect<T>;
      };
  featuredImage?: T;
  excerpt?: T;
  category?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  name?: T;
  items?:
    | T
    | {
        page?: T;
        anchor?: T;
        url?: T;
        label?: T;
        type?: T;
        newTab?: T;
        children?:
          | T
          | {
              page?: T;
              anchor?: T;
              url?: T;
              label?: T;
              type?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  orientation?: T;
  variant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors".
 */
export interface Color {
  id: number;
  colors?:
    | {
        label: string;
        /**
         * It will be used as a CSS class/variable — without spaces
         */
        value: string;
        hex?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  blocks?:
    | (
        | BlockHolderLevel0BlockProps
        | MenuBlockProps
        | HeadingBlockProps
        | RichTextBlockProps
        | ImageBlockProps
        | ButtonBlockProps
        | TabsBlockProps
        | SliderBlockProps
        | AccordionBlockProps
        | CTABlockProps
        | TestimonialsBlockProps
        | StatsBlockProps
        | TeamBlockProps
      )[]
    | null;
  variant?: ('default' | 'transparent' | 'minimal') | null;
  sticky?: ('none' | 'sticky' | 'sticky-up') | null;
  containerType?: ('container-xl' | 'container-lg' | 'container' | 'container-xs') | null;
  /**
   * Optional — custom ID attribute on the header element
   */
  htmlId?: string | null;
  paddingTop?: number | null;
  paddingBottom?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Used in browser tab, SEO fallback, and logo alt text
   */
  siteTitle: string;
  /**
   * Short description — used in default SEO if no meta description is set
   */
  tagline?: string | null;
  /**
   * Displayed in header — recommended SVG or PNG with transparency
   */
  logo?: (number | null) | Media;
  /**
   * Optional — used when header is on dark background
   */
  logoDark?: (number | null) | Media;
  /**
   * ICO, PNG ili SVG — preporučeno 32×32px ili 512×512px
   */
  favicon?: (number | null) | Media;
  /**
   * PNG, 180×180px — koristi se na iOS home screen
   */
  appleTouchIcon?: (number | null) | Media;
  /**
   * Fallback vrijednosti kada stranica nema custom SEO
   */
  defaultMeta?: {
    /**
     * Ako je prazno, koristi Site Title
     */
    title?: string | null;
    /**
     * Preporučeno: 120–160 karaktera
     */
    description?: string | null;
    /**
     * Za social sharing — preporučeno 1200×630px
     */
    ogImage?: (number | null) | Media;
  };
  /**
   * Koristi %s za naziv stranice, %site za naziv sajta
   */
  titleTemplate?: string | null;
  robots?: ('index, follow' | 'noindex, nofollow' | 'index, nofollow' | 'noindex, follow') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors_select".
 */
export interface ColorsSelect<T extends boolean = true> {
  colors?:
    | T
    | {
        label?: T;
        value?: T;
        hex?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        blockHolder0?: T | BlockHolderLevel0BlockPropsSelect<T>;
        menu?: T | MenuBlockPropsSelect<T>;
        heading?: T | HeadingBlockPropsSelect<T>;
        richText?: T | RichTextBlockPropsSelect<T>;
        image?: T | ImageBlockPropsSelect<T>;
        button?: T | ButtonBlockPropsSelect<T>;
        tabs?: T | TabsBlockPropsSelect<T>;
        slider?: T | SliderBlockPropsSelect<T>;
        accordion?: T | AccordionBlockPropsSelect<T>;
        cta?: T | CTABlockPropsSelect<T>;
        testimonials?: T | TestimonialsBlockPropsSelect<T>;
        stats?: T | StatsBlockPropsSelect<T>;
        team?: T | TeamBlockPropsSelect<T>;
      };
  variant?: T;
  sticky?: T;
  containerType?: T;
  htmlId?: T;
  paddingTop?: T;
  paddingBottom?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  tagline?: T;
  logo?: T;
  logoDark?: T;
  favicon?: T;
  appleTouchIcon?: T;
  defaultMeta?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  titleTemplate?: T;
  robots?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}