/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    colors: Color;
  };
  globalsSelect: {
    colors: ColorsSelect<false> | ColorsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  layout?:
    | {
        blocks?:
          | (
              | {
                  blocks?:
                    | (
                        | {
                            content?:
                              | (
                                  | {
                                      title?: string | null;
                                      variant?: 'default' | null;
                                      titleTag?: ('h1' | 'h2' | 'h3' | 'h4' | 'p' | 'span') | null;
                                      color?: string | null;
                                      id?: string | null;
                                      blockName?: string | null;
                                      blockType: 'heading';
                                    }
                                  | {
                                      text?: {
                                        root: {
                                          type: string;
                                          children: {
                                            type: any;
                                            version: number;
                                            [k: string]: unknown;
                                          }[];
                                          direction: ('ltr' | 'rtl') | null;
                                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                          indent: number;
                                          version: number;
                                        };
                                        [k: string]: unknown;
                                      } | null;
                                      variant?: 'default' | null;
                                      color?: string | null;
                                      id?: string | null;
                                      blockName?: string | null;
                                      blockType: 'richText';
                                    }
                                  | {
                                      text: string;
                                      linkType?: ('internal' | 'external') | null;
                                      internalLink?: (number | null) | Page;
                                      externalUrl?: string | null;
                                      newTab?: boolean | null;
                                      variant?: ('primary' | 'secondary' | 'ghost' | 'outline') | null;
                                      hasIcon?: boolean | null;
                                      iconType?: ('picker' | 'customSvg') | null;
                                      icon?: string | null;
                                      customSvg?: (number | null) | Media;
                                      iconPosition?: ('left' | 'right') | null;
                                      id?: string | null;
                                      blockName?: string | null;
                                      blockType: 'button';
                                    }
                                )[]
                              | null;
                            verticalPosition?: ('top' | 'center' | 'bottom' | 'space-between' | 'space-around') | null;
                            horizontalPosition?: ('left' | 'center' | 'right') | null;
                            variant?: 'default' | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'textBlock';
                          }
                        | {
                            image?: (number | null) | Media;
                            aspectRatio?: ('auto' | '1/1' | '4/3' | '16/9' | '3/2' | '9/16' | 'custom') | null;
                            /**
                             * Format: 16/9, 4/3, 1/1...
                             */
                            customAspectRatio?: string | null;
                            overlay?: {
                              enabled?: boolean | null;
                              color?: string | null;
                              /**
                               * 0 - 100
                               */
                              opacity?: number | null;
                            };
                            variant?: 'default' | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'image';
                          }
                        | {
                            text: string;
                            linkType?: ('internal' | 'external') | null;
                            internalLink?: (number | null) | Page;
                            externalUrl?: string | null;
                            newTab?: boolean | null;
                            variant?: ('primary' | 'secondary' | 'ghost' | 'outline') | null;
                            hasIcon?: boolean | null;
                            iconType?: ('picker' | 'customSvg') | null;
                            icon?: string | null;
                            customSvg?: (number | null) | Media;
                            iconPosition?: ('left' | 'right') | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'button';
                          }
                      )[]
                    | null;
                  layout?: ('block' | 'flex' | 'grid') | null;
                  gap?: number | null;
                  variant?: 'default' | null;
                  flexDirection?: ('row' | 'column' | 'row-reverse' | 'column-reverse') | null;
                  flexJustify?:
                    | ('start' | 'center' | 'end' | 'stretch' | 'space-between' | 'space-around' | 'space-evenly')
                    | null;
                  flexAlign?: ('start' | 'center' | 'end' | 'stretch') | null;
                  flexWrap?: ('nowrap' | 'wrap' | 'wrap-reverse') | null;
                  gridMode?: ('auto' | 'custom') | null;
                  gridJustifyItems?: ('start' | 'center' | 'end' | 'stretch') | null;
                  gridAlignItems?: ('start' | 'center' | 'end' | 'stretch') | null;
                  gridAutoRepeat?: ('auto-fill' | 'auto-fit') | null;
                  gridAutoMinValue?: number | null;
                  gridAutoMinUnit?: ('px' | '%' | 'rem') | null;
                  gridAutoMax?: ('1fr' | '2fr' | '3fr' | '100%') | null;
                  gridColumns?:
                    | {
                        value?: number | null;
                        unit?: ('fr' | 'px' | '%' | 'rem' | 'auto' | 'min-content' | 'max-content') | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'blockHolder';
                }
              | {
                  layout?: ('imageLeft' | 'imageRight') | null;
                  image: number | Media;
                  textContent?: {
                    content?:
                      | (
                          | {
                              title?: string | null;
                              variant?: 'default' | null;
                              titleTag?: ('h1' | 'h2' | 'h3' | 'h4' | 'p' | 'span') | null;
                              color?: string | null;
                              id?: string | null;
                              blockName?: string | null;
                              blockType: 'heading';
                            }
                          | {
                              text?: {
                                root: {
                                  type: string;
                                  children: {
                                    type: any;
                                    version: number;
                                    [k: string]: unknown;
                                  }[];
                                  direction: ('ltr' | 'rtl') | null;
                                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                  indent: number;
                                  version: number;
                                };
                                [k: string]: unknown;
                              } | null;
                              variant?: 'default' | null;
                              color?: string | null;
                              id?: string | null;
                              blockName?: string | null;
                              blockType: 'richText';
                            }
                          | {
                              text: string;
                              linkType?: ('internal' | 'external') | null;
                              internalLink?: (number | null) | Page;
                              externalUrl?: string | null;
                              newTab?: boolean | null;
                              variant?: ('primary' | 'secondary' | 'ghost' | 'outline') | null;
                              hasIcon?: boolean | null;
                              iconType?: ('picker' | 'customSvg') | null;
                              icon?: string | null;
                              customSvg?: (number | null) | Media;
                              iconPosition?: ('left' | 'right') | null;
                              id?: string | null;
                              blockName?: string | null;
                              blockType: 'button';
                            }
                        )[]
                      | null;
                    verticalPosition?: ('top' | 'center' | 'bottom' | 'space-between' | 'space-around') | null;
                    horizontalPosition?: ('left' | 'center' | 'right') | null;
                    variant?: 'default' | null;
                  };
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'mediaContent';
                }
              | {
                  settings?: {
                    orientation?: ('horizontal' | 'vertical') | null;
                    /**
                     * Space between slides in px
                     */
                    spaceBetween?: number | null;
                    slidesPerView?: number | null;
                  };
                  slides?:
                    | {
                        image: number | Media;
                        caption?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'slider';
                }
              | {
                  content?:
                    | (
                        | {
                            title?: string | null;
                            variant?: 'default' | null;
                            titleTag?: ('h1' | 'h2' | 'h3' | 'h4' | 'p' | 'span') | null;
                            color?: string | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'heading';
                          }
                        | {
                            text?: {
                              root: {
                                type: string;
                                children: {
                                  type: any;
                                  version: number;
                                  [k: string]: unknown;
                                }[];
                                direction: ('ltr' | 'rtl') | null;
                                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                indent: number;
                                version: number;
                              };
                              [k: string]: unknown;
                            } | null;
                            variant?: 'default' | null;
                            color?: string | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'richText';
                          }
                        | {
                            text: string;
                            linkType?: ('internal' | 'external') | null;
                            internalLink?: (number | null) | Page;
                            externalUrl?: string | null;
                            newTab?: boolean | null;
                            variant?: ('primary' | 'secondary' | 'ghost' | 'outline') | null;
                            hasIcon?: boolean | null;
                            iconType?: ('picker' | 'customSvg') | null;
                            icon?: string | null;
                            customSvg?: (number | null) | Media;
                            iconPosition?: ('left' | 'right') | null;
                            id?: string | null;
                            blockName?: string | null;
                            blockType: 'button';
                          }
                      )[]
                    | null;
                  verticalPosition?: ('top' | 'center' | 'bottom' | 'space-between' | 'space-around') | null;
                  horizontalPosition?: ('left' | 'center' | 'right') | null;
                  variant?: 'default' | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'textBlock';
                }
            )[]
          | null;
        settings?: {
          widthType?: ('fullWidth' | 'boxed') | null;
          containerType?: ('container-xl' | 'container-lg' | 'container' | 'container-xs') | null;
          variant?: 'default' | null;
          paddingTop?: number | null;
          paddingBottom?: number | null;
          heightType?: ('fullHeight' | 'auto') | null;
          backgroundType?: ('blank' | 'color' | 'gradient' | 'image') | null;
          colorTheme?: string | null;
          gradientTheme?: ('warm' | 'cool') | null;
          bgImage?: (number | null) | Media;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'section';
      }[]
    | null;
  /**
   * Title tag appearing in Google results (recommended up to 60 characters).
   */
  seoTitle?: string | null;
  /**
   * Meta description for search engines (recommended up to 160 characters).
   */
  seoDescription?: string | null;
  /**
   * Social media share image.
   */
  seoImage?: (number | null) | Media;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        section?:
          | T
          | {
              blocks?:
                | T
                | {
                    blockHolder?:
                      | T
                      | {
                          blocks?:
                            | T
                            | {
                                textBlock?:
                                  | T
                                  | {
                                      content?:
                                        | T
                                        | {
                                            heading?:
                                              | T
                                              | {
                                                  title?: T;
                                                  variant?: T;
                                                  titleTag?: T;
                                                  color?: T;
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                            richText?:
                                              | T
                                              | {
                                                  text?: T;
                                                  variant?: T;
                                                  color?: T;
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                            button?:
                                              | T
                                              | {
                                                  text?: T;
                                                  linkType?: T;
                                                  internalLink?: T;
                                                  externalUrl?: T;
                                                  newTab?: T;
                                                  variant?: T;
                                                  hasIcon?: T;
                                                  iconType?: T;
                                                  icon?: T;
                                                  customSvg?: T;
                                                  iconPosition?: T;
                                                  id?: T;
                                                  blockName?: T;
                                                };
                                          };
                                      verticalPosition?: T;
                                      horizontalPosition?: T;
                                      variant?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                image?:
                                  | T
                                  | {
                                      image?: T;
                                      aspectRatio?: T;
                                      customAspectRatio?: T;
                                      overlay?:
                                        | T
                                        | {
                                            enabled?: T;
                                            color?: T;
                                            opacity?: T;
                                          };
                                      variant?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                button?:
                                  | T
                                  | {
                                      text?: T;
                                      linkType?: T;
                                      internalLink?: T;
                                      externalUrl?: T;
                                      newTab?: T;
                                      variant?: T;
                                      hasIcon?: T;
                                      iconType?: T;
                                      icon?: T;
                                      customSvg?: T;
                                      iconPosition?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                              };
                          layout?: T;
                          gap?: T;
                          variant?: T;
                          flexDirection?: T;
                          flexJustify?: T;
                          flexAlign?: T;
                          flexWrap?: T;
                          gridMode?: T;
                          gridJustifyItems?: T;
                          gridAlignItems?: T;
                          gridAutoRepeat?: T;
                          gridAutoMinValue?: T;
                          gridAutoMinUnit?: T;
                          gridAutoMax?: T;
                          gridColumns?:
                            | T
                            | {
                                value?: T;
                                unit?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    mediaContent?:
                      | T
                      | {
                          layout?: T;
                          image?: T;
                          textContent?:
                            | T
                            | {
                                content?:
                                  | T
                                  | {
                                      heading?:
                                        | T
                                        | {
                                            title?: T;
                                            variant?: T;
                                            titleTag?: T;
                                            color?: T;
                                            id?: T;
                                            blockName?: T;
                                          };
                                      richText?:
                                        | T
                                        | {
                                            text?: T;
                                            variant?: T;
                                            color?: T;
                                            id?: T;
                                            blockName?: T;
                                          };
                                      button?:
                                        | T
                                        | {
                                            text?: T;
                                            linkType?: T;
                                            internalLink?: T;
                                            externalUrl?: T;
                                            newTab?: T;
                                            variant?: T;
                                            hasIcon?: T;
                                            iconType?: T;
                                            icon?: T;
                                            customSvg?: T;
                                            iconPosition?: T;
                                            id?: T;
                                            blockName?: T;
                                          };
                                    };
                                verticalPosition?: T;
                                horizontalPosition?: T;
                                variant?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    slider?:
                      | T
                      | {
                          settings?:
                            | T
                            | {
                                orientation?: T;
                                spaceBetween?: T;
                                slidesPerView?: T;
                              };
                          slides?:
                            | T
                            | {
                                image?: T;
                                caption?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    textBlock?:
                      | T
                      | {
                          content?:
                            | T
                            | {
                                heading?:
                                  | T
                                  | {
                                      title?: T;
                                      variant?: T;
                                      titleTag?: T;
                                      color?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                richText?:
                                  | T
                                  | {
                                      text?: T;
                                      variant?: T;
                                      color?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                                button?:
                                  | T
                                  | {
                                      text?: T;
                                      linkType?: T;
                                      internalLink?: T;
                                      externalUrl?: T;
                                      newTab?: T;
                                      variant?: T;
                                      hasIcon?: T;
                                      iconType?: T;
                                      icon?: T;
                                      customSvg?: T;
                                      iconPosition?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                              };
                          verticalPosition?: T;
                          horizontalPosition?: T;
                          variant?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              settings?:
                | T
                | {
                    widthType?: T;
                    containerType?: T;
                    variant?: T;
                    paddingTop?: T;
                    paddingBottom?: T;
                    heightType?: T;
                    backgroundType?: T;
                    colorTheme?: T;
                    gradientTheme?: T;
                    bgImage?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors".
 */
export interface Color {
  id: number;
  colors?:
    | {
        label: string;
        /**
         * It will be used as a CSS class/variable — without spaces
         */
        value: string;
        hex?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors_select".
 */
export interface ColorsSelect<T extends boolean = true> {
  colors?:
    | T
    | {
        label?: T;
        value?: T;
        hex?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}